# shellcheck disable=SC2034 # Used by `main_keymap.zsh`
SLACK_KEYMAP=(
	'cmd-shift-d # Show / hide sidebar in Home'
	'ctrl-1 # Home'
	'ctrl-3 # Activity (cmd-shift-m)'
	'ctrl-4 # Later'
	'cmd-[ # Back in history'
	'cmd-] # Forward in history'
	''
	'alt-shift-up # Go to unread channel above'
	'alt-shift-down # Go to unread channel below'
	'shift-pageUp # Scroll to previous day'
	'shift-pageDown # Scroll to next day'
	'up # Move to previous message'
	'down # Move to next message'
	'right # Open a thread (t)'
	'cmd-. # Close right pane'
	''
	'cmd-up # Edit last message'
	'e # Edit'
	'del # Delete'
	'r # React (cmd-shift-\)'
	'a # Save / remove from Later'
	'u # Mark unread'
	''
	'cmd-t # Jump to a conversation'
	'cmd-n # New message'
	'cmd-g # Search'
	'cmd-f # Search current conversation'
	''
	'cmd-shift-y # Set a status'
	'cmd-/ # List keyboard shortcuts'
)
