# shellcheck disable=SC2034 # Used by `main_keymap.zsh`
NOTION_KEYMAP=(
	'cmd-t # Search & open in a new tab'
	'cmd-k # Search & open in the current tab'
	''
	'cmd+alt+3 # Turn into heading 3'
	'cmd+alt+4 # Turn into a to-do list ([])'
	'cmd+alt+5 # Turn into a bullet list (-/*)'
	'cmd+alt+6 # Turn into a numbered list (1.)'
	'cmd+alt+7 # Turn into a toggle list (>)'
	'cmd+alt+8 # Turn into a code block (```)'
	'cmd+alt+9 # Turn into a page (/p)'
	'cmd+alt+0 # Turn into plain text'
	'" # Turn into a quote (|)'
	'/ # Turn into ...'
	''
	'cmd+{enter} # Open a page / toggle an item'
	'cmd+shift+u # Go up a level'
	'cmd+[ # Go back'
	'cmd+] # Go forward'
	''
	'cmd+l # Copy link to page'
	'cmd+ctrl+l # Copy link to block'
	''
	'{esc} # Select the current section'
	'cmd-d # Duplicate the current section'
	'cmd-shift-{up} # Move the current section up'
	'cmd-shift-{down} # Move the current section down'
	''
	'cmd-e # Wrap the current text with ``'
)
