ALL_KEYMAP=(
	'a # Show `args_keymap`'
	's # Show `aws_keymap`'
	'd # Show `docker_keymap`'
	'g # Show `git_keymap`'
	'h # Show `github_keymap`'
	'k # Show `kubectl_keymap`'
	'm # Show `main_keymap`'
	'n # Show `nav_keymap`'
	'o # Show `other_keymap`'
	't # Show `terraform_keymap`'
	'z # Show `zsh_keymap`'
	''
	'i # Show `intellij_all_keymap`'
	'ia # Show `intellij_alt_keymap`'
	'ic # Show `intellij_cmd_keymap`'
	'it # Show `intellij_ctrl_keymap`'
	'vv # Show `vimium_keymap`'
	'v # Show `vimium_search_keymap`'
)
