# shellcheck disable=SC2034 # Used by `main_keymap.zsh`
VI_KEYMAP=(
	'k / {up} # Up'
	'j / {down} # Down'
	'h / {left} # Left'
	'l / {right} # Right'
	'w # Jump forward one word'
	'b # Jump backward one word'
	'0 # Jump to beginning of line'
	'$ # Jump to end of line'
	'gg # Jump to top'
	'G # Jump to bottom'
	''
	'i # Insert before the cursor'
	'a # Insert after the cursor'
	'A # Insert at the end of the line'
	'o # Insert a new line below'
	'O # Insert a new line above'
	''
	'x # Delete character under the cursor'
	'X # Delete character before the cursor'
	'r # Replace character under the cursor'
	'R # Replace characters under the cursor'
	''
	'dd # Delete the current line'
	'yy # Yank the current line'
	'p # Paste the yanked text after the cursor'
	'P # Paste the yanked text before the cursor'
	''
	'u # Undo'
	'ctrl-r # Redo'
	''
	'/ # Search forward'
	'? # Search backward'
	'n # Next match'
	'N # Previous match'
	''
	'w # Save'
	'q # Quit'
	'wq # Save and quit'
	'q! # Quit without saving'
	''
	':set number # Show line numbers'
	':set nonumber # Hide line numbers'
	':set list # Show whitespace'
	':set nolist # Hide whitespace'
	':set wrap # Wrap lines'
	':set nowrap # Unwrap lines'
	':syntax on # Enable syntax highlighting'
	':syntax off # Disable syntax highlighting'
	':%s/{old}/{new}/g # Replace all `old` with `new`'
)
