# shellcheck disable=SC2034 # Used by `main_keymap.zsh`
NOTION_KEYMAP=(
	'cmd+alt+3 # Turn into heading 3'
	'cmd+alt+4 # Turn into a to-do list ([])'
	'cmd+alt+5 # Turn into a bullet list (-/*)'
	'cmd+alt+6 # Turn into a numbered list (1.)'
	'cmd+alt+7 # Turn into a toggle list (>)'
	'cmd+alt+8 # Turn into a code block (```)'
	'cmd+alt+9 # Turn into a page (/p)'
	'cmd+alt+0 # Turn into plain text'
	'" # Turn into a quote (|)'
	'/ # Turn into ...'
	''
	'cmd+[enter] # Take action'
	'cmd+shift+u # Go up a level'
	''
	'cmd-t # Open in a new tab'
	'cmd-k # Open in the current tab'
	''
	'esc # Select current section'
	'cmd-d # Wrap current section'
	'cmd-shift-[up] # Move current section up'
	'cmd-shift-[down] # Move current section down'
	''
	'cmd-e # Wrap current text with ``'
)
