ALL_KEYMAP=(
	'a # Custom aliases: args_keymap.zsh'
	's # Custom aliases: aws_keymap.zsh'
	'd # Custom aliases: docker_keymap.zsh'
	'g # Custom aliases: git_keymap.zsh'
	'h # Custom aliases: github_keymap.zsh'
	'k # Custom aliases: kubectl_keymap.zsh'
	'm # Custom aliases: main_keymap.zsh'
	'n # Custom aliases: nav_keymap.zsh'
	'o # Custom aliases: other_keymap.zsh'
	't # Custom aliases: terraform_keymap.zsh'
	'z # Custom aliases: zsh_keymap.zsh'
	''
	'i # Custom shortcuts: intellij_all.zsh'
	'ia # Custom shortcuts: intellij_alt_keymap.zsh'
	'ic # Custom shortcuts: intellij_cmd_keymap.zsh'
	'it # Custom shortcuts: intellij_ctrl_keymap.zsh'
	'vv # Custom shortcuts: vimium_keymap.zsh'
	'v # Custom shortcuts: vimium_search_keymap.zsh'
)
