INTELLIJ_ALL_NAMESPACE='intellij_all_keymap'
INTELLIJ_ALL_ALIAS='i'

INTELLIJ_ALL_KEYMAP=(
	${INTELLIJ_CMD_KEYMAP[@]}
	${INTELLIJ_CTRL_KEYMAP[@]}
	${INTELLIJ_ALT_KEYMAP[@]}
)

keymap_init $INTELLIJ_ALL_NAMESPACE $INTELLIJ_ALL_ALIAS "${INTELLIJ_ALL_KEYMAP[@]}"

function intellij_all_keymap {
	keymap_show $INTELLIJ_ALL_NAMESPACE $INTELLIJ_ALL_ALIAS \
		${#INTELLIJ_ALL_KEYMAP} "${INTELLIJ_ALL_KEYMAP[@]}" "$@"
}
