function 0 { args_keymap_n $ "$@"; } # Last arg
function 1 { args_keymap_n "$0" "$@"; }
function 2 { args_keymap_n "$0" "$@"; }
function 3 { args_keymap_n "$0" "$@"; }
function 4 { args_keymap_n "$0" "$@"; }
function 5 { args_keymap_n "$0" "$@"; }
function 6 { args_keymap_n "$0" "$@"; }
function 7 { args_keymap_n "$0" "$@"; }
function 8 { args_keymap_n "$0" "$@"; }
function 9 { args_keymap_n "$0" "$@"; }
function 10 { args_keymap_n "$0" "$@"; }
function 11 { args_keymap_n "$0" "$@"; }
function 12 { args_keymap_n "$0" "$@"; }
function 13 { args_keymap_n "$0" "$@"; }
function 14 { args_keymap_n "$0" "$@"; }
function 15 { args_keymap_n "$0" "$@"; }
function 16 { args_keymap_n "$0" "$@"; }
function 17 { args_keymap_n "$0" "$@"; }
function 18 { args_keymap_n "$0" "$@"; }
function 19 { args_keymap_n "$0" "$@"; }
function 20 { args_keymap_n "$0" "$@"; }
function 21 { args_keymap_n "$0" "$@"; }
function 22 { args_keymap_n "$0" "$@"; }
function 23 { args_keymap_n "$0" "$@"; }
function 24 { args_keymap_n "$0" "$@"; }
function 25 { args_keymap_n "$0" "$@"; }
function 26 { args_keymap_n "$0" "$@"; }
function 27 { args_keymap_n "$0" "$@"; }
function 28 { args_keymap_n "$0" "$@"; }
function 29 { args_keymap_n "$0" "$@"; }
function 30 { args_keymap_n "$0" "$@"; }
function 31 { args_keymap_n "$0" "$@"; }
function 32 { args_keymap_n "$0" "$@"; }
function 33 { args_keymap_n "$0" "$@"; }
function 34 { args_keymap_n "$0" "$@"; }
function 35 { args_keymap_n "$0" "$@"; }
function 36 { args_keymap_n "$0" "$@"; }
function 37 { args_keymap_n "$0" "$@"; }
function 38 { args_keymap_n "$0" "$@"; }
function 39 { args_keymap_n "$0" "$@"; }
function 40 { args_keymap_n "$0" "$@"; }
function 41 { args_keymap_n "$0" "$@"; }
function 42 { args_keymap_n "$0" "$@"; }
function 43 { args_keymap_n "$0" "$@"; }
function 44 { args_keymap_n "$0" "$@"; }
function 45 { args_keymap_n "$0" "$@"; }
function 46 { args_keymap_n "$0" "$@"; }
function 47 { args_keymap_n "$0" "$@"; }
function 48 { args_keymap_n "$0" "$@"; }
function 49 { args_keymap_n "$0" "$@"; }
function 50 { args_keymap_n "$0" "$@"; }
function 51 { args_keymap_n "$0" "$@"; }
function 52 { args_keymap_n "$0" "$@"; }
function 53 { args_keymap_n "$0" "$@"; }
function 54 { args_keymap_n "$0" "$@"; }
function 55 { args_keymap_n "$0" "$@"; }
function 56 { args_keymap_n "$0" "$@"; }
function 57 { args_keymap_n "$0" "$@"; }
function 58 { args_keymap_n "$0" "$@"; }
function 59 { args_keymap_n "$0" "$@"; }
function 60 { args_keymap_n "$0" "$@"; }
function 61 { args_keymap_n "$0" "$@"; }
function 62 { args_keymap_n "$0" "$@"; }
function 63 { args_keymap_n "$0" "$@"; }
function 64 { args_keymap_n "$0" "$@"; }
function 65 { args_keymap_n "$0" "$@"; }
function 66 { args_keymap_n "$0" "$@"; }
function 67 { args_keymap_n "$0" "$@"; }
function 68 { args_keymap_n "$0" "$@"; }
function 69 { args_keymap_n "$0" "$@"; }
function 70 { args_keymap_n "$0" "$@"; }
function 71 { args_keymap_n "$0" "$@"; }
function 72 { args_keymap_n "$0" "$@"; }
function 73 { args_keymap_n "$0" "$@"; }
function 74 { args_keymap_n "$0" "$@"; }
function 75 { args_keymap_n "$0" "$@"; }
function 76 { args_keymap_n "$0" "$@"; }
function 77 { args_keymap_n "$0" "$@"; }
function 78 { args_keymap_n "$0" "$@"; }
function 79 { args_keymap_n "$0" "$@"; }
function 80 { args_keymap_n "$0" "$@"; }
function 81 { args_keymap_n "$0" "$@"; }
function 82 { args_keymap_n "$0" "$@"; }
function 83 { args_keymap_n "$0" "$@"; }
function 84 { args_keymap_n "$0" "$@"; }
function 85 { args_keymap_n "$0" "$@"; }
function 86 { args_keymap_n "$0" "$@"; }
function 87 { args_keymap_n "$0" "$@"; }
function 88 { args_keymap_n "$0" "$@"; }
function 89 { args_keymap_n "$0" "$@"; }
function 90 { args_keymap_n "$0" "$@"; }
function 91 { args_keymap_n "$0" "$@"; }
function 92 { args_keymap_n "$0" "$@"; }
function 93 { args_keymap_n "$0" "$@"; }
function 94 { args_keymap_n "$0" "$@"; }
function 95 { args_keymap_n "$0" "$@"; }
function 96 { args_keymap_n "$0" "$@"; }
function 97 { args_keymap_n "$0" "$@"; }
function 98 { args_keymap_n "$0" "$@"; }
function 99 { args_keymap_n "$0" "$@"; }
function 100 { args_keymap_n "$0" "$@"; }
