VIMIUM_SEARCH_KEYMAP=(
	'o # Go Links'
	''
	'c # Github Code Search (TENGF)'
	'cd # Github Code Search (DBE)'
	'cc # Github Code Search'
	'r # Github Repo Search (TENGF)'
	'rd # Github Repo Search (DBE)'
	'rr # Github Repo Search'
	''
	'a # Datadog App APM (Prod)'
	'aa # Datadog App APM (QA)'
	'd # Datadog DB APM (Prod)'
	'dd # Datadog DB APM (QA)'
	'l # Datadog Logs (Prod)'
	'll # Datadog Logs (QA)'
	''
	'dl # Datadog Dashboard Lists (go/dl)'
	'mm # Datadog Manage Monitors (go/mm)'
	'ms # Datadog Metrics Summary (go/ms)'
	''
	'- # ECR (rel-2025.{MM.DD})'
	'e # ECR (Prod)'
	'ee # ECR (QA)'
	''
	'g # Google Gmail'
	'gc # Google Calendar'
	'gd # Google Drive'
	'gi # Google Images'
	'gm # Google Maps'
	''
	'h # Datadog K8s Pods (Prod)'
	'hh # Datadog K8s Pods (QA)'
	't # Datadog K8s Deployments (Prod)'
	'tt # Datadog K8s Deployments (QA)'
	'te # Datadog K8s Deployment Events (Prod)'
	'tee # Datadog K8s Deployment Events (QA)'
	'tl # Datadog K8s Deployment Logs (Prod)'
	'tll # Datadog K8s Deployment Logs (QA)'
	''
	'j # Jira Ticket'
	'jj # Jira Ticket (INCI)'
	'jc # Jira Ticket (CHANGE)'
	'jt # Jira Ticket (TENGF)'
	''
	'js # Jira Sprint'
	'jb # Jira Backlog'
	''
	'se # AWS EC2'
	'sl # AWS Load Balancers'
	'sm # AWS Secrets Manager'
	''
	'z # E.ggtimer (10m)'
	'zz # E.ggtimer (1m)'
)
