VIMIUM_SEARCH_KEYMAP=(
	'c # Confluence'
	''
	'da # Datadog APM Prod'
	'daa # Datadog APM QA'
	'ddl # Datadog Dashboard Lists'
	'di # Datadog Infrastructure Prod'
	'dii # Datadog Infrastructure QA'
	'dl # Datadog Logs'
	'dmm # Datadog Manage Monitors'
	'dms # Datadog Metrics Summary'
	''
	'gc # Google Calendar'
	'gd # Google Drive'
	'gg # Google Gmail'
	'gi # Google Images'
	'gm # Google Maps'
	''
	'h # Github Search (TENGF)'
	'hh # Github Search'
	'hr # Github Repos'
	''
	'j # Jira Ticket'
	'jj # Jira Ticket (TENGF)'
	'jc # Jira Ticket (CHANGE)'
	'ji # Jira Ticket (INCI)'
	'js # Jira Sprint'
	'jb # Jira Backlog'
	''
	'o # Go Links'
	''
	'se # AWS EC2'
	'sl # AWS Load Balancers'
	'sm # AWS Secrets Manager'
	''
	't # E.ggtimer (10m)'
	'tt # E.ggtimer (1m)'
	''
	'y # Yelp'
)
