VIMIUM_KEYMAP=(
	'o # Vomnibar.activateInNewTab'
	'O # Vomnibar.activateBookmarksInNewTab'
	'e # enterInsertMode'
	'- # focusInput'
	''
	'a # LinkHints.activateMode'
	'A # LinkHints.activateModeToOpenInNewForegroundTab'
	'; # LinkHints.activateModeToOpenInNewTab'
	': # LinkHints.activateModeWithQueue'
	'i # LinkHints.activateModeToOpenIncognito'
	''
	'Y # LinkHints.activateModeToCopyLinkUrl'
	'y # copyCurrentUrl'
	'p # openCopiedUrlInNewTab'
	'd # duplicateTab'
	'r # reload'
	'u # goUp'
	'U # goToRoot'
	'c # removeTab'
	'C # closeTabsOnRight'
	''
	'h # scrollPageUp'
	't # scrollPageDown'
	'H # goPrevious'
	'T # goNext'
	'm # scrollToTop'
	'w # scrollToBottom'
	''
	'{up} # scrollUp'
	'{down} # scrollDown'
	'{left} # scrollLeft'
	'{right} # scrollRight'
	''
	'n # previousTab'
	's # nextTab'
	'N # moveTabLeft'
	'S # moveTabRight'
	'v # goBack'
	'z # goForward'
)
