VIMIUM_SEARCH_KEYMAP=(
	'a # Datadog APM (Prod)'
	'aa # Datadog APM (QA)'
	''
	'c # Confluence (TENGF)'
	'cc # Confluence'
	''
	'dl # Datadog Dashboard Lists (go/dl)'
	''
	'e # Github Search (TENGF)'
	'ee # Github Search'
	''
	'g # Google Gmail'
	'gc # Google Calendar'
	'gd # Google Drive'
	'gi # Google Images'
	'gm # Google Maps'
	''
	'h # Github Repos (TENGF)'
	'hh # Github Repos'
	''
	'i # Datadog Infrastructure (Prod)'
	'ii # Datadog Infrastructure (QA)'
	''
	'j # Jira Ticket'
	'jb # Jira Backlog'
	'jc # Jira Ticket (CHANGE)'
	'ji # Jira Ticket (INCI)'
	'jj # Jira Ticket (TENGF)'
	'js # Jira Sprint'
	''
	'kd # Datadog Kubernetes Deployments'
	'kp # Datadog Kubernetes Pods'
	''
	'l # Datadog Logs (Prod)'
	'll # Datadog Logs (QA)'
	''
	'mm # Datadog Manage Monitors (go/mm)'
	'ms # Datadog Metrics Summary (go/ms)'
	''
	'o # Go Links'
	''
	'se # AWS EC2'
	'sl # AWS Load Balancers'
	'sm # AWS Secrets Manager'
	''
	't # E.ggtimer (10m)'
	'tt # E.ggtimer (1m)'
	''
	'y # Yelp'
	'yt # YouTube'
)
