VIMIUM_KEYMAP=(
	'a # LinkHints.activateMode'
	'; # LinkHints.activateModeToOpenInNewTab'
	'o # Vomnibar.activateInNewTab'
	'q # Vomnibar.activateBookmarksInNewTab'
	'i # enterInsertMode'
	''
	'h # scrollPageUp'
	't # scrollPageDown'
	'H # goPrevious'
	'T # goNext'
	'm # scrollToTop'
	'w # scrollToBottom'
	''
	'<up> # scrollUp'
	'<down> # scrollDown'
	'<left> # scrollLeft'
	'<right> # scrollRight'
	''
	'n # previousTab'
	's # nextTab'
	'N # moveTabLeft'
	'S # moveTabRight'
	'v # goBack'
	'z # goForward'
	''
	'c # removeTab'
	'C # closeTabsOnRight'
	'r # reload'
	'd # duplicateTab'
	'p # openCopiedUrlInNewTab'
	'y # copyCurrentUrl'
	''
	'- # focusInput'
)
