TERRAFORM_NAMESPACE='terraform_keymap'
TERRAFORM_ALIAS='t'
TERRAFORM_DOT="${TERRAFORM_ALIAS}${KEYMAP_DOT}"
TERRAFORM_PLAN_MAX_AGE=5 # In minutes; override with `t.a <max age>`

TERRAFORM_KEYMAP=(
	"${TERRAFORM_ALIAS} <terraform command> # Pass through"
	''
	"${TERRAFORM_DOT}t <match>* <-mismatch>* # List manifests & filter"
	''
	"${TERRAFORM_DOT}i # Init"
	"${TERRAFORM_DOT}iu # Init & upgrade"
	"${TERRAFORM_DOT}ir # Init & reconfigure"
	"${TERRAFORM_DOT}im # Init & migrate state"
	"${TERRAFORM_DOT}e # Load secret env vars"
	''
	"${TERRAFORM_DOT}v (i,iu,ir,im,e)? # Validate"
	"${TERRAFORM_DOT}p (i,iu,ir,im,e)? # Plan"
	"${TERRAFORM_DOT}g # Upload 'tfplan' as a gist"
	"${TERRAFORM_DOT}a <max age in min>? # Apply 'tfplan' (Default: ${TERRAFORM_PLAN_MAX_AGE})"
	''
	"${TERRAFORM_DOT}s <match>* <-mismatch>* # List states & filter"
	"${TERRAFORM_DOT}sd <state> # Delete state"
	"${TERRAFORM_DOT}sr <before> <after> # Rename state"
	"${TERRAFORM_DOT}ss <state> # Show state"
	"${TERRAFORM_DOT}st <state> # Taint state"
	"${TERRAFORM_DOT}su <state> # Untaint state"
	''
	"${TERRAFORM_DOT}c # Clean"
	"${TERRAFORM_DOT}cc # Clean & clear plugin cache"
	"${TERRAFORM_DOT}d # Destroy"
	"${TERRAFORM_DOT}f <path>? # Format (Default: CWD)"
	"${TERRAFORM_DOT}n <var name>? # Start console or print var in CWD"
	"${TERRAFORM_DOT}nn <var name>? # Start console or print var in 'tf-debug'"
	"${TERRAFORM_DOT}o # Show output"
	"${TERRAFORM_DOT}u <lock id>? # Unlock (Default: Pasteboard)"
	''
	"${TERRAFORM_DOT}m # Open diff from pasteboard in TextMate"
	''
	"${TERRAFORM_DOT}r # (Reserved: Translate chars)"
)

keymap_init $TERRAFORM_NAMESPACE $TERRAFORM_ALIAS "${TERRAFORM_KEYMAP[@]}"

source "$ZSHRC_SRC_DIR/$TERRAFORM_NAMESPACE/terraform_commands.zsh"
function terraform_keymap {
	# If the first arg is a `terraform` command, pass it through
	for command in "${TERRAFORM_COMMANDS[@]}"; do
		if [[ $command == "$1" ]]; then
			terraform "$@"
			return
		fi
	done

	keymap_show $TERRAFORM_NAMESPACE $TERRAFORM_ALIAS \
		${#TERRAFORM_KEYMAP} "${TERRAFORM_KEYMAP[@]}" "$@"
}

#
# Key mappings (Alphabetized)
#

# Sources
source "$ZSHRC_SRC_DIR/$TERRAFORM_NAMESPACE/terraform_helpers.zsh"

# Constants
TERRAFORM_VARS=( # To be overwritten by `ZSHRC_SECRETS`
	'var_name_1 secret_name_1'
	'var_name_2 secret_name_2'
)

function terraform_keymap_a {
	local max_age=${1:-$TERRAFORM_PLAN_MAX_AGE}

	# Apply the plan generated by `t.p` and reviewed via `t.g`
	if [[ ! -e tfplan ]]; then
		red_bar 'No tfplan to apply'
		return 1
	fi

	local age=$(( $(date +%s) - $(stat -f %m tfplan) ))
	echo
	gray_fg "tfplan is $(( age / 60 ))m $(( age % 60 ))s old"

	# Reject a plan left idle too long, as it may no longer match reality
	if [[ $age -gt $(( max_age * 60 )) ]]; then
		red_bar "tfplan is stale (max ${max_age}m)"
		return 1
	fi

	confirm 'Apply tfplan' || return 1

	terraform apply tfplan
}

function terraform_keymap_c {
	rm -rf tfplan .terraform ~/.terraform.d
}

function terraform_keymap_cc {
	rm -rf tfplan .terraform ~/.terraform.d ~/.terraform.cache
}

function terraform_keymap_d {
	confirm 'Terraform destroy' || return 1

	terraform destroy
}

function terraform_keymap_e {
	local fields
	local var_name
	local secret_name

	for var in "${TERRAFORM_VARS[@]}"; do
		fields=("${=var}")
		var_name="TF_VAR_${fields[1]}"
		secret_name="${fields[2]}"

		echo_eval "export $var_name=\$(aws_keymap_mg $secret_name)"

		# If env var was not set, exit with error
		[[ -z ${(P)var_name} ]] && return 1
	done

	return 0
}

function terraform_keymap_f {
	local target_path=${1:-.}

	terraform fmt -recursive "$target_path"
}

function terraform_keymap_g {
	terraform show -bw tfplan | sed 's/user_data.*/user_data [REDACTED]/' | gh gist create --web
}

function terraform_keymap_i {
	mkdir -p ~/.terraform.cache; terraform init
}

function terraform_keymap_im {
	terraform init -migrate-state
}

function terraform_keymap_ir {
	terraform init -reconfigure
}

function terraform_keymap_iu {
	terraform init -upgrade
}

function terraform_keymap_m {
	local plan; plan=$(pbpaste)

	if [[ -z $plan ]]; then
		red_bar 'No plan in pasteboard'
		return
	fi

	local diff; diff=$(echo "$plan" | terraform_helpers_diff)

	if [[ -z $diff ]]; then
		red_bar 'No diff found in pasteboard'
		return
	fi

	# Not named `tfplan`; nothing is saved, and `t.a` applies the real file
	echo "$diff" | mate -m 'pasted plan' -t source.terraform
}

function terraform_keymap_n {
	local var=$1

	if [[ -z $var ]]; then
		terraform console
	else
		echo "local.$var" | terraform console
	fi
}

function terraform_keymap_nn {
	pushd ~/GitHub/jasonzhao6/scratch/tf-debug > /dev/null || return
	terraform_keymap_n "$@"
	popd > /dev/null || return
}

function terraform_keymap_o {
	terraform output
}

function terraform_keymap_p {
	local options=$1

	# Drop any stale plan first, so `tfplan` exists only if this plan succeeded
	terraform_helpers_init "$options" && rm -f tfplan && terraform plan -out=tfplan
}

function terraform_keymap_s {
	local filters=("$@")

	terraform state list | sed "s/.*/'&'/" | args_keymap_s "${filters[@]}"
}

function terraform_keymap_sd {
	local state=$1

	confirm "Delete state '$state'" || return 1

	terraform state rm "$state"
}

function terraform_keymap_sr {
	terraform state mv "$1" "$2"
}

function terraform_keymap_ss {
	local state=$1

	terraform state show "$state"
}

function terraform_keymap_st {
	local state=$1

	terraform taint "$state"
}

function terraform_keymap_su {
	local state=$1

	terraform untaint "$state"
}

function terraform_keymap_t {
	local filters=("$@")

	ls -- **/main.tf | trim 0 8 | args_keymap_s "${filters[@]}"
}

function terraform_keymap_u {
	local id=${1:-$(pbpaste)}

	terraform force-unlock "$id"
}

function terraform_keymap_v {
	local options=$1

	terraform_helpers_init "$options" && terraform validate
}
